### ISSUE TITLE
All the images are failing to download , error as fail 

### ISSUE THREAD

**Issue by VijayMukkala** [somvirs57/image_scraping#1]
When I try copying the code in Jupyter notebook and in the final step after the scroll , the images get selected but the images doesnt download into the folder . Also at the end of the image it gets 'fail'.
From the video, it is mentioned as when an src is null then it fails but I do the same operations but no luck .
Can you help me with this

**Comment by somvirs57** [comment]
Hi Vijay, I believe you got the solution to this.
